//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace nestedmasterpage
{


    public partial class WebForm1
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new nestedmasterpage.NestedMasterPage1 Master
        {
            get
            {
                return ((nestedmasterpage.NestedMasterPage1)(base.Master));
            }
        }
    }
}
